version: '3'
services:
  python3:
    build: .
    container_name: 'py3-container'
    working_dir: '/var/docker-python'
    tty: true
    volumes:
      - ./app:/var/docker-python/app
    environment:
      - SNOWFLAKE_ACCOUNT=${SNOWFLAKE_ACCOUNT}
      - SNOWFLAKE_USERNAME=${SNOWFLAKE_USERNAME}
      - SNOWFLAKE_PASSWORD=${SNOWFLAKE_PASSWORD}
      - DBT_PROFILE_TARGET=${DBT_PROFILE_TARGET}
      - TZ=Asia/Tokyo
